define(function(require) {

    "use strict";

    var internalAbnormalConditions = [
        {
            "caseId": 431681,
            "eventId": -1,
            "state": "OHIO",
            "district": "Columbus",
            "startTime": 1367423280000,
            "isolated": "N",
            "details": "At Marion: 138kv cap bank 7 non-critical alarm",
            "troubleInfo": "At Marion: 138kv cap bank 7 non-critical alarm",
            "title": "Marion Road",
            "doubleCircuitOutage": "N",
            "properRelayOperation": "Y",
            "manual": "N",
            "diffEventStart": "N",
            "priority": 3,
            "topsAnalysisComplete": "N",
            "topsApproved": "N",
            "createdBy": 873,
            "createdDate": 1367444040000,
            "modifiedBy": 1678,
            "modifiedDate": 1367446320000,
            "isTemplate": "N",
            "abnormCondEquipments": [],
            "abnormCondStations": [
                {
                    "stationName": "Marion Road",
                    "torStationId": 857,
                    "regionName": "Columbus",
                    "areaName": "Columbus",
                    "transmissionDispatchCenterId": 23,
                    "transmissionDispatchCenter": "Columbus Central",
                    "transmissionDispatchCenterPhone": "614-413-2180",
                    "distributionDispatchCenterId": 12,
                    "distributionDispatchCenter": "Columbus Metro",
                    "distributionDispatchCenterPhone": "614-413-7099",
                    "hasOpenCheckIns": false,
                    "phone": "614-444-1732",
                    "county": "FRANKLIN",
                    "state": "OH",
                    "directions": "869 MARION RD  COLUMBUS",
                    "latitude": "39.92222867",
                    "longitude": "-82.9712871",
                    "contacts": "614 462 3333",
                    "district": "COL",
                    "restrictedFlag": false,
                    "hazardFlag": false,
                    "refreshDate": 1393952077531,
                    "stationId": 691,
                    "hasHazard": false
                }
            ],
            "abnormCondLines": []
        },
        {
            "caseId": 408733,
            "eventId": -1,
            "state": "OHIO",
            "district": "Columbus",
            "startTime": 1215799260000,
            "isolated": "N",
            "details": "DO NOT OPERATE. Control rod broken.",
            "title": "HAYDEN",
            "doubleCircuitOutage": "N",
            "properRelayOperation": "N",
            "manual": "N",
            "diffEventStart": "Y",
            "priority": 1,
            "topsAnalysisComplete": "N",
            "topsApproved": "N",
            "createdBy": 1776,
            "createdDate": 1215799260000,
            "modifiedBy": 5928,
            "modifiedDate": 1362162300000,
            "isTemplate": "N",
            "deviceId": 34896,
            "abnormCondEquipments": [
                {
                    "equipmentId": 13284,
                    "equipmentType": "AB",
                    "equipmentName": "Hyatt",
                    "equipmentFullName": "Hyatt",
                    "stationId": 658,
                    "voltage": "345",
                    "enableFlag": "Y",
                    "userOrg": 123,
                    "lastUpdatedBy": "TOA_APP",
                    "lastUpdatedDate": 1326488872000,
                    "createdBy": "TOA_APP",
                    "createdDate": 1285105526000,
                    "newEquip": "F",
                    "foreign": "F",
                    "historical": "F",
                    "torEquipId": 39934,
                    "torStationId": 796,
                    "equipmentOwner": 30,
                    "symbolName": " ",
                    "description": "Hyatt"
                }
            ],
            "abnormCondStations": [],
            "abnormCondLines": []
        },
        {
            "caseId": 437986,
            "eventId": 554886,
            "state": "VIRGINIA",
            "startTime": 1370560740000,
            "isolated": "Y",
            "details": "Transfer Trip Abnormal Alarms/pilot wire abnormal\r\nREQ 10915",
            "operatingArrangements": "No clearance issued.",
            "troubleInfo": "Opossum Creek - Joshua Falls PW & TT remains cutout due to trouble.",
            "title": "Joshua Falls - Opossum Creek (138 kV); Opossum Creek - Reusens (138 kV)",
            "doubleCircuitOutage": "N",
            "properRelayOperation": "Y",
            "manual": "N",
            "diffEventStart": "N",
            "topsAnalysisComplete": "N",
            "topsApproved": "N",
            "createdBy": 1048,
            "createdDate": 1370561280000,
            "modifiedBy": 1342,
            "modifiedDate": 1371498420000,
            "isTemplate": "N",
            "abnormCondEquipments": [
                {
                    "equipmentId": 11725,
                    "equipmentType": "CB",
                    "equipmentName": "East Lynchburg",
                    "equipmentFullName": "East Lynchburg",
                    "stationId": 525,
                    "voltage": "138",
                    "enableFlag": "Y",
                    "emsEquipmentId": "5469",
                    "userOrg": 123,
                    "lastUpdatedBy": "TOA_APP",
                    "lastUpdatedDate": 1326488926000,
                    "createdBy": "TOA_APP",
                    "createdDate": 1285105528000,
                    "newEquip": "F",
                    "foreign": "F",
                    "historical": "F",
                    "torEquipId": 2571,
                    "torStationId": 309,
                    "emsName": "OPOSSUMCB1  ",
                    "emsVoltage": 138,
                    "equipmentOwner": 30,
                    "symbolName": "B1",
                    "description": "East Lynchburg"
                }
            ],
            "abnormCondStations": [],
            "abnormCondLines": [
                {
                    "lineId": 168,
                    "circuit": "FM76      ",
                    "enableFlag": "Y",
                    "userOrg": 123,
                    "lineFullName": "Opossum Creek - Reusens",
                    "underGround": "F",
                    "torCircuitId": 168,
                    "mileage": 14,
                    "historical": "F",
                    "voltageCir": 138,
                    "aepNonAep": "T",
                    "emsName": "GRAVESMI1REUSENS 1  ",
                    "emsId": 1881,
                    "nercRep": "F",
                    "kv": 138,
                    "ddcRegion": "Roanoke",
                    "dispRegion": "Roanoke-South",
                    "dispatchRegion": "Roanoke-South",
                    "ddc": "Roanoke",
                    "emsVoltageNumber": 138,
                    "createdBy": "TOA_APP",
                    "createdDate": 1285105615000,
                    "lastUpdatedBy": "TOA_APP",
                    "lastUpdatedDate": 1320651698000
                },
                {
                    "lineId": 110,
                    "circuit": "FG55      ",
                    "enableFlag": "Y",
                    "userOrg": 123,
                    "lineFullName": "East Lynchburg - Joshua Falls",
                    "underGround": "F",
                    "torCircuitId": 110,
                    "mileage": 3,
                    "historical": "F",
                    "voltageCir": 138,
                    "aepNonAep": "T",
                    "emsName": "ELYNCHBU1JOSHUAFA1  ",
                    "emsId": 1818,
                    "nercRep": "F",
                    "kv": 138,
                    "ddcRegion": "Roanoke",
                    "dispRegion": "Roanoke-South",
                    "dispatchRegion": "Roanoke-South",
                    "ddc": "Roanoke",
                    "emsVoltageNumber": 138,
                    "createdBy": "TOA_APP",
                    "createdDate": 1285105614000,
                    "lastUpdatedBy": "TOA_APP",
                    "lastUpdatedDate": 1320651662000
                },
                {
                    "lineId": 131,
                    "circuit": "FH63      ",
                    "enableFlag": "Y",
                    "userOrg": 123,
                    "lineFullName": "Joshua Falls - Reusens",
                    "underGround": "F",
                    "torCircuitId": 131,
                    "mileage": 9,
                    "historical": "F",
                    "voltageCir": 138,
                    "aepNonAep": "T",
                    "emsName": "MONEL   1REUSENS 1  ",
                    "emsId": 1996,
                    "nercRep": "F",
                    "kv": 138,
                    "ddcRegion": "Roanoke",
                    "dispRegion": "Roanoke-South",
                    "dispatchRegion": "Roanoke-South",
                    "ddc": "Roanoke",
                    "emsVoltageNumber": 138,
                    "createdBy": "TOA_APP",
                    "createdDate": 1285105614000,
                    "lastUpdatedBy": "TOA_APP",
                    "lastUpdatedDate": 1320651662000
                },
                {
                    "lineId": 167,
                    "circuit": "FM73      ",
                    "enableFlag": "Y",
                    "userOrg": 123,
                    "lineFullName": "Opossum Creek - Peaksview",
                    "underGround": "F",
                    "torCircuitId": 167,
                    "mileage": 1,
                    "historical": "F",
                    "voltageCir": 138,
                    "aepNonAep": "T",
                    "emsName": "OPOSSUMC1PEAKSVIE1  ",
                    "emsId": 2047,
                    "nercRep": "F",
                    "kv": 138,
                    "ddcRegion": "Roanoke",
                    "dispRegion": "Roanoke-South",
                    "dispatchRegion": "Roanoke-South",
                    "ddc": "Roanoke",
                    "emsVoltageNumber": 138,
                    "createdBy": "TOA_APP",
                    "createdDate": 1285105613000,
                    "lastUpdatedBy": "TOA_APP",
                    "lastUpdatedDate": 1320651701000
                },
                {
                    "lineId": 109,
                    "circuit": "FG48      ",
                    "enableFlag": "Y",
                    "userOrg": 123,
                    "lineFullName": "East Lynchburg - Opossum Creek",
                    "underGround": "F",
                    "torCircuitId": 109,
                    "mileage": 2,
                    "historical": "F",
                    "voltageCir": 138,
                    "aepNonAep": "T",
                    "emsName": "ELYNCHBU1OPOSSUMC1  ",
                    "emsId": 1819,
                    "nercRep": "F",
                    "kv": 138,
                    "ddcRegion": "Roanoke",
                    "dispRegion": "Roanoke-South",
                    "dispatchRegion": "Roanoke-South",
                    "ddc": "Roanoke",
                    "emsVoltageNumber": 138,
                    "createdBy": "TOA_APP",
                    "createdDate": 1285105614000,
                    "lastUpdatedBy": "TOA_APP",
                    "lastUpdatedDate": 1320651662000
                },
                {
                    "lineId": 132,
                    "circuit": "FH66      ",
                    "enableFlag": "Y",
                    "userOrg": 123,
                    "lineFullName": "Joshua Falls - Opossum Creek",
                    "underGround": "F",
                    "torCircuitId": 132,
                    "mileage": 5,
                    "historical": "F",
                    "voltageCir": 138,
                    "aepNonAep": "T",
                    "emsName": "JOSHUAFA1OPOSSUMC1  ",
                    "emsId": 1934,
                    "nercRep": "F",
                    "kv": 138,
                    "ddcRegion": "Roanoke",
                    "dispRegion": "Roanoke-South",
                    "dispatchRegion": "Roanoke-South",
                    "ddc": "Roanoke",
                    "emsVoltageNumber": 138,
                    "createdBy": "TOA_APP",
                    "createdDate": 1285105614000,
                    "lastUpdatedBy": "TOA_APP",
                    "lastUpdatedDate": 1320651662000
                }
            ]
        },
        {
            "caseId": 432904,
            "eventId": -1,
            "state": "VIRGINIA",
            "startTime": 1368077220000,
            "isolated": "N",
            "details": "Recurring CB MA Alarm Delle Minsub 138kV Alarm ",
            "troubleInfo": "Low hydraulic fluid on Tr 1 138kV CB G2 due to leak.  Personnel unable to locate source of leak at this time.\r\n\r\nNotify Dale Arrington immediately anytime this alarm seals in as per M. Cheek and C. Foggy.",
            "title": "Joshua Falls - Tr. 1 138KV - CB G2 ",
            "doubleCircuitOutage": "N",
            "properRelayOperation": "Y",
            "manual": "N",
            "diffEventStart": "N",
            "topsAnalysisComplete": "N",
            "topsApproved": "N",
            "createdBy": 1354,
            "createdDate": 1368089760000,
            "modifiedBy": 1378,
            "modifiedDate": 1368206280000,
            "isTemplate": "N",
            "abnormCondEquipments": [
                {
                    "equipmentId": 8548,
                    "equipmentType": "CB",
                    "equipmentName": "Tr. 1",
                    "equipmentFullName": "Tr. 1",
                    "stationId": 35,
                    "voltage": "138",
                    "enableFlag": "Y",
                    "emsEquipmentId": "5186",
                    "userOrg": 123,
                    "lastUpdatedBy": "TOA_APP",
                    "lastUpdatedDate": 1326488936000,
                    "createdBy": "TOA_APP",
                    "createdDate": 1285105528000,
                    "newEquip": "F",
                    "foreign": "F",
                    "historical": "F",
                    "torEquipId": 2395,
                    "torStationId": 222,
                    "emsName": "JOSHUAFAG2  ",
                    "emsVoltage": 138,
                    "equipmentOwner": 30,
                    "symbolName": "G2",
                    "description": "Tr. 1"
                },
                {
                    "equipmentId": 18012,
                    "equipmentType": "BUS",
                    "stationId": 35,
                    "voltage": "138",
                    "enableFlag": "Y",
                    "userOrg": 123,
                    "lastUpdatedBy": "TOA_APP",
                    "lastUpdatedDate": 1326488927000,
                    "createdBy": "TOA_APP",
                    "createdDate": 1285105528000,
                    "newEquip": "F",
                    "foreign": "F",
                    "historical": "F",
                    "torEquipId": 10492,
                    "torStationId": 222,
                    "equipmentOwner": 30,
                    "symbolName": "2         "
                },
                {
                    "equipmentId": 11687,
                    "equipmentType": "BUS",
                    "stationId": 35,
                    "voltage": "138",
                    "enableFlag": "Y",
                    "userOrg": 123,
                    "lastUpdatedBy": "TOA_APP",
                    "lastUpdatedDate": 1326488924000,
                    "createdBy": "TOA_APP",
                    "createdDate": 1285105528000,
                    "newEquip": "F",
                    "foreign": "F",
                    "historical": "F",
                    "torEquipId": 10650,
                    "torStationId": 222,
                    "equipmentOwner": 30,
                    "symbolName": "1         "
                }
            ],
            "abnormCondStations": [],
            "abnormCondLines": [
                {
                    "lineId": 131,
                    "circuit": "FH63      ",
                    "enableFlag": "Y",
                    "userOrg": 123,
                    "lineFullName": "Joshua Falls - Reusens",
                    "underGround": "F",
                    "torCircuitId": 131,
                    "mileage": 9,
                    "historical": "F",
                    "voltageCir": 138,
                    "aepNonAep": "T",
                    "emsName": "MONEL   1REUSENS 1  ",
                    "emsId": 1996,
                    "nercRep": "F",
                    "kv": 138,
                    "ddcRegion": "Roanoke",
                    "dispRegion": "Roanoke-South",
                    "dispatchRegion": "Roanoke-South",
                    "ddc": "Roanoke",
                    "emsVoltageNumber": 138,
                    "createdBy": "TOA_APP",
                    "createdDate": 1285105614000,
                    "lastUpdatedBy": "TOA_APP",
                    "lastUpdatedDate": 1320651662000
                }
            ]
        },
        {
            "caseId": 441036,
            "eventId": 561586,
            "state": "OHIO",
            "district": "Newark",
            "startTime": 1371896160000,
            "isolated": "N",
            "details": "S.O. 14616 Rev. 19\r\nWest Morrison SW installed on feed to GE Hebron (Momentive). SW is bypassed w/ Switches open and tagged until ready to put into service. (See Drawing at Central Desk)",
            "title": "Dow Chemical - Kaiser Junction Sw. (69 kV)",
            "doubleCircuitOutage": "N",
            "properRelayOperation": "Y",
            "manual": "N",
            "diffEventStart": "N",
            "topsAnalysisComplete": "N",
            "topsApproved": "N",
            "createdBy": 1678,
            "createdDate": 1371898620000,
            "modifiedBy": 1561,
            "modifiedDate": 1372112280000,
            "isTemplate": "N",
            "abnormCondEquipments": [
                {
                    "equipmentId": 11438,
                    "equipmentType": "CB",
                    "equipmentName": "West Hebron/Kaiser Junction",
                    "equipmentFullName": "West Hebron/Kaiser Junction",
                    "stationId": 4763,
                    "voltage": "69",
                    "enableFlag": "Y",
                    "userOrg": 123,
                    "lastUpdatedBy": "TOA_APP",
                    "lastUpdatedDate": 1326488930000,
                    "createdBy": "TOA_APP",
                    "createdDate": 1285105528000,
                    "newEquip": "F",
                    "foreign": "F",
                    "historical": "F",
                    "torEquipId": 48241,
                    "torStationId": 12115,
                    "equipmentOwner": 30,
                    "symbolName": "A",
                    "description": "West Hebron/Kaiser Junction"
                },
                {
                    "equipmentId": 5356,
                    "equipmentType": "AB",
                    "equipmentName": "North Hebron  ",
                    "equipmentFullName": "North Hebron  ",
                    "stationId": 2327,
                    "voltage": "69",
                    "enableFlag": "Y",
                    "userOrg": 123,
                    "lastUpdatedBy": "TOA_APP",
                    "lastUpdatedDate": 1326488872000,
                    "createdBy": "TOA_APP",
                    "createdDate": 1285105525000,
                    "newEquip": "F",
                    "foreign": "F",
                    "historical": "F",
                    "torEquipId": 35690,
                    "torStationId": 5565,
                    "equipmentOwner": 30,
                    "symbolName": " ",
                    "description": "North Hebron  "
                },
                {
                    "equipmentId": 14751,
                    "equipmentType": "AB",
                    "equipmentName": "Kaiser Junction",
                    "equipmentFullName": "Kaiser Junction",
                    "stationId": 4763,
                    "voltage": "69",
                    "enableFlag": "Y",
                    "userOrg": 123,
                    "lastUpdatedBy": "TOA_APP",
                    "lastUpdatedDate": 1326488904000,
                    "createdBy": "TOA_APP",
                    "createdDate": 1285105527000,
                    "newEquip": "F",
                    "foreign": "F",
                    "historical": "F",
                    "torEquipId": 48247,
                    "torStationId": 12115,
                    "equipmentOwner": 30,
                    "symbolName": "  ",
                    "description": "Kaiser Junction"
                }
            ],
            "abnormCondStations": [],
            "abnormCondLines": [
                {
                    "lineId": 857,
                    "circuit": "HG17      ",
                    "enableFlag": "Y",
                    "userOrg": 123,
                    "lineFullName": "Dow Chemical - Kaiser Junction Sw.",
                    "underGround": "F",
                    "torCircuitId": 857,
                    "mileage": 4,
                    "historical": "F",
                    "voltageCir": 69,
                    "aepNonAep": "T",
                    "nercRep": "F",
                    "kv": 69,
                    "ddcRegion": "Columbus",
                    "dispRegion": "Columbus Central",
                    "dispatchRegion": "Ohio-South",
                    "ddc": "Columbus",
                    "createdBy": "TOA_APP",
                    "createdDate": 1285105614000,
                    "lastUpdatedBy": "TOA_APP",
                    "lastUpdatedDate": 1320651676000
                }
            ]
        },
        {
            "caseId": 431681,
            "eventId": -1,
            "state": "OHIO",
            "district": "Columbus",
            "startTime": 1367423280000,
            "isolated": "N",
            "details": "At Marion: 138kv cap bank 7 non-critical alarm",
            "troubleInfo": "At Marion: 138kv cap bank 7 non-critical alarm",
            "title": "Marion Road",
            "doubleCircuitOutage": "N",
            "properRelayOperation": "Y",
            "manual": "N",
            "diffEventStart": "N",
            "priority": 3,
            "topsAnalysisComplete": "N",
            "topsApproved": "N",
            "createdBy": 873,
            "createdDate": 1367444040000,
            "modifiedBy": 1678,
            "modifiedDate": 1367446320000,
            "isTemplate": "N",
            "abnormCondEquipments": [],
            "abnormCondStations": [
                {
                    "stationName": "Marion Road",
                    "torStationId": 857,
                    "regionName": "Columbus",
                    "areaName": "Columbus",
                    "transmissionDispatchCenterId": 23,
                    "transmissionDispatchCenter": "Columbus Central",
                    "transmissionDispatchCenterPhone": "614-413-2180",
                    "distributionDispatchCenterId": 12,
                    "distributionDispatchCenter": "Columbus Metro",
                    "distributionDispatchCenterPhone": "614-413-7099",
                    "hasOpenCheckIns": false,
                    "phone": "614-444-1732",
                    "county": "FRANKLIN",
                    "state": "OH",
                    "directions": "869 MARION RD  COLUMBUS",
                    "latitude": "39.92222867",
                    "longitude": "-82.9712871",
                    "contacts": "614 462 3333",
                    "district": "COL",
                    "restrictedFlag": false,
                    "hazardFlag": false,
                    "refreshDate": 1393952077531,
                    "stationId": 691,
                    "hasHazard": false
                }
            ],
            "abnormCondLines": []
        },
        {
            "caseId": 408733,
            "eventId": -1,
            "state": "OHIO",
            "district": "Columbus",
            "startTime": 1215799260000,
            "isolated": "N",
            "details": "DO NOT OPERATE. Control rod broken.",
            "title": "HAYDEN",
            "doubleCircuitOutage": "N",
            "properRelayOperation": "N",
            "manual": "N",
            "diffEventStart": "Y",
            "priority": 1,
            "topsAnalysisComplete": "N",
            "topsApproved": "N",
            "createdBy": 1776,
            "createdDate": 1215799260000,
            "modifiedBy": 5928,
            "modifiedDate": 1362162300000,
            "isTemplate": "N",
            "deviceId": 34896,
            "abnormCondEquipments": [
                {
                    "equipmentId": 13284,
                    "equipmentType": "AB",
                    "equipmentName": "Hyatt",
                    "equipmentFullName": "Hyatt",
                    "stationId": 658,
                    "voltage": "345",
                    "enableFlag": "Y",
                    "userOrg": 123,
                    "lastUpdatedBy": "TOA_APP",
                    "lastUpdatedDate": 1326488872000,
                    "createdBy": "TOA_APP",
                    "createdDate": 1285105526000,
                    "newEquip": "F",
                    "foreign": "F",
                    "historical": "F",
                    "torEquipId": 39934,
                    "torStationId": 796,
                    "equipmentOwner": 30,
                    "symbolName": " ",
                    "description": "Hyatt"
                }
            ],
            "abnormCondStations": [],
            "abnormCondLines": []
        },
        {
            "caseId": 437986,
            "eventId": 554886,
            "state": "VIRGINIA",
            "startTime": 1370560740000,
            "isolated": "Y",
            "details": "Transfer Trip Abnormal Alarms/pilot wire abnormal\r\nREQ 10915",
            "operatingArrangements": "No clearance issued.",
            "troubleInfo": "Opossum Creek - Joshua Falls PW & TT remains cutout due to trouble.",
            "title": "Joshua Falls - Opossum Creek (138 kV); Opossum Creek - Reusens (138 kV)",
            "doubleCircuitOutage": "N",
            "properRelayOperation": "Y",
            "manual": "N",
            "diffEventStart": "N",
            "topsAnalysisComplete": "N",
            "topsApproved": "N",
            "createdBy": 1048,
            "createdDate": 1370561280000,
            "modifiedBy": 1342,
            "modifiedDate": 1371498420000,
            "isTemplate": "N",
            "abnormCondEquipments": [
                {
                    "equipmentId": 11725,
                    "equipmentType": "CB",
                    "equipmentName": "East Lynchburg",
                    "equipmentFullName": "East Lynchburg",
                    "stationId": 525,
                    "voltage": "138",
                    "enableFlag": "Y",
                    "emsEquipmentId": "5469",
                    "userOrg": 123,
                    "lastUpdatedBy": "TOA_APP",
                    "lastUpdatedDate": 1326488926000,
                    "createdBy": "TOA_APP",
                    "createdDate": 1285105528000,
                    "newEquip": "F",
                    "foreign": "F",
                    "historical": "F",
                    "torEquipId": 2571,
                    "torStationId": 309,
                    "emsName": "OPOSSUMCB1  ",
                    "emsVoltage": 138,
                    "equipmentOwner": 30,
                    "symbolName": "B1",
                    "description": "East Lynchburg"
                }
            ],
            "abnormCondStations": [],
            "abnormCondLines": [
                {
                    "lineId": 168,
                    "circuit": "FM76      ",
                    "enableFlag": "Y",
                    "userOrg": 123,
                    "lineFullName": "Opossum Creek - Reusens",
                    "underGround": "F",
                    "torCircuitId": 168,
                    "mileage": 14,
                    "historical": "F",
                    "voltageCir": 138,
                    "aepNonAep": "T",
                    "emsName": "GRAVESMI1REUSENS 1  ",
                    "emsId": 1881,
                    "nercRep": "F",
                    "kv": 138,
                    "ddcRegion": "Roanoke",
                    "dispRegion": "Roanoke-South",
                    "dispatchRegion": "Roanoke-South",
                    "ddc": "Roanoke",
                    "emsVoltageNumber": 138,
                    "createdBy": "TOA_APP",
                    "createdDate": 1285105615000,
                    "lastUpdatedBy": "TOA_APP",
                    "lastUpdatedDate": 1320651698000
                },
                {
                    "lineId": 110,
                    "circuit": "FG55      ",
                    "enableFlag": "Y",
                    "userOrg": 123,
                    "lineFullName": "East Lynchburg - Joshua Falls",
                    "underGround": "F",
                    "torCircuitId": 110,
                    "mileage": 3,
                    "historical": "F",
                    "voltageCir": 138,
                    "aepNonAep": "T",
                    "emsName": "ELYNCHBU1JOSHUAFA1  ",
                    "emsId": 1818,
                    "nercRep": "F",
                    "kv": 138,
                    "ddcRegion": "Roanoke",
                    "dispRegion": "Roanoke-South",
                    "dispatchRegion": "Roanoke-South",
                    "ddc": "Roanoke",
                    "emsVoltageNumber": 138,
                    "createdBy": "TOA_APP",
                    "createdDate": 1285105614000,
                    "lastUpdatedBy": "TOA_APP",
                    "lastUpdatedDate": 1320651662000
                },
                {
                    "lineId": 131,
                    "circuit": "FH63      ",
                    "enableFlag": "Y",
                    "userOrg": 123,
                    "lineFullName": "Joshua Falls - Reusens",
                    "underGround": "F",
                    "torCircuitId": 131,
                    "mileage": 9,
                    "historical": "F",
                    "voltageCir": 138,
                    "aepNonAep": "T",
                    "emsName": "MONEL   1REUSENS 1  ",
                    "emsId": 1996,
                    "nercRep": "F",
                    "kv": 138,
                    "ddcRegion": "Roanoke",
                    "dispRegion": "Roanoke-South",
                    "dispatchRegion": "Roanoke-South",
                    "ddc": "Roanoke",
                    "emsVoltageNumber": 138,
                    "createdBy": "TOA_APP",
                    "createdDate": 1285105614000,
                    "lastUpdatedBy": "TOA_APP",
                    "lastUpdatedDate": 1320651662000
                },
                {
                    "lineId": 167,
                    "circuit": "FM73      ",
                    "enableFlag": "Y",
                    "userOrg": 123,
                    "lineFullName": "Opossum Creek - Peaksview",
                    "underGround": "F",
                    "torCircuitId": 167,
                    "mileage": 1,
                    "historical": "F",
                    "voltageCir": 138,
                    "aepNonAep": "T",
                    "emsName": "OPOSSUMC1PEAKSVIE1  ",
                    "emsId": 2047,
                    "nercRep": "F",
                    "kv": 138,
                    "ddcRegion": "Roanoke",
                    "dispRegion": "Roanoke-South",
                    "dispatchRegion": "Roanoke-South",
                    "ddc": "Roanoke",
                    "emsVoltageNumber": 138,
                    "createdBy": "TOA_APP",
                    "createdDate": 1285105613000,
                    "lastUpdatedBy": "TOA_APP",
                    "lastUpdatedDate": 1320651701000
                },
                {
                    "lineId": 109,
                    "circuit": "FG48      ",
                    "enableFlag": "Y",
                    "userOrg": 123,
                    "lineFullName": "East Lynchburg - Opossum Creek",
                    "underGround": "F",
                    "torCircuitId": 109,
                    "mileage": 2,
                    "historical": "F",
                    "voltageCir": 138,
                    "aepNonAep": "T",
                    "emsName": "ELYNCHBU1OPOSSUMC1  ",
                    "emsId": 1819,
                    "nercRep": "F",
                    "kv": 138,
                    "ddcRegion": "Roanoke",
                    "dispRegion": "Roanoke-South",
                    "dispatchRegion": "Roanoke-South",
                    "ddc": "Roanoke",
                    "emsVoltageNumber": 138,
                    "createdBy": "TOA_APP",
                    "createdDate": 1285105614000,
                    "lastUpdatedBy": "TOA_APP",
                    "lastUpdatedDate": 1320651662000
                },
                {
                    "lineId": 132,
                    "circuit": "FH66      ",
                    "enableFlag": "Y",
                    "userOrg": 123,
                    "lineFullName": "Joshua Falls - Opossum Creek",
                    "underGround": "F",
                    "torCircuitId": 132,
                    "mileage": 5,
                    "historical": "F",
                    "voltageCir": 138,
                    "aepNonAep": "T",
                    "emsName": "JOSHUAFA1OPOSSUMC1  ",
                    "emsId": 1934,
                    "nercRep": "F",
                    "kv": 138,
                    "ddcRegion": "Roanoke",
                    "dispRegion": "Roanoke-South",
                    "dispatchRegion": "Roanoke-South",
                    "ddc": "Roanoke",
                    "emsVoltageNumber": 138,
                    "createdBy": "TOA_APP",
                    "createdDate": 1285105614000,
                    "lastUpdatedBy": "TOA_APP",
                    "lastUpdatedDate": 1320651662000
                }
            ]
        },
        {
            "caseId": 432904,
            "eventId": -1,
            "state": "VIRGINIA",
            "startTime": 1368077220000,
            "isolated": "N",
            "details": "Recurring CB MA Alarm Delle Minsub 138kV Alarm ",
            "troubleInfo": "Low hydraulic fluid on Tr 1 138kV CB G2 due to leak.  Personnel unable to locate source of leak at this time.\r\n\r\nNotify Dale Arrington immediately anytime this alarm seals in as per M. Cheek and C. Foggy.",
            "title": "Joshua Falls - Tr. 1 138KV - CB G2 ",
            "doubleCircuitOutage": "N",
            "properRelayOperation": "Y",
            "manual": "N",
            "diffEventStart": "N",
            "topsAnalysisComplete": "N",
            "topsApproved": "N",
            "createdBy": 1354,
            "createdDate": 1368089760000,
            "modifiedBy": 1378,
            "modifiedDate": 1368206280000,
            "isTemplate": "N",
            "abnormCondEquipments": [
                {
                    "equipmentId": 8548,
                    "equipmentType": "CB",
                    "equipmentName": "Tr. 1",
                    "equipmentFullName": "Tr. 1",
                    "stationId": 35,
                    "voltage": "138",
                    "enableFlag": "Y",
                    "emsEquipmentId": "5186",
                    "userOrg": 123,
                    "lastUpdatedBy": "TOA_APP",
                    "lastUpdatedDate": 1326488936000,
                    "createdBy": "TOA_APP",
                    "createdDate": 1285105528000,
                    "newEquip": "F",
                    "foreign": "F",
                    "historical": "F",
                    "torEquipId": 2395,
                    "torStationId": 222,
                    "emsName": "JOSHUAFAG2  ",
                    "emsVoltage": 138,
                    "equipmentOwner": 30,
                    "symbolName": "G2",
                    "description": "Tr. 1"
                },
                {
                    "equipmentId": 18012,
                    "equipmentType": "BUS",
                    "stationId": 35,
                    "voltage": "138",
                    "enableFlag": "Y",
                    "userOrg": 123,
                    "lastUpdatedBy": "TOA_APP",
                    "lastUpdatedDate": 1326488927000,
                    "createdBy": "TOA_APP",
                    "createdDate": 1285105528000,
                    "newEquip": "F",
                    "foreign": "F",
                    "historical": "F",
                    "torEquipId": 10492,
                    "torStationId": 222,
                    "equipmentOwner": 30,
                    "symbolName": "2         "
                },
                {
                    "equipmentId": 11687,
                    "equipmentType": "BUS",
                    "stationId": 35,
                    "voltage": "138",
                    "enableFlag": "Y",
                    "userOrg": 123,
                    "lastUpdatedBy": "TOA_APP",
                    "lastUpdatedDate": 1326488924000,
                    "createdBy": "TOA_APP",
                    "createdDate": 1285105528000,
                    "newEquip": "F",
                    "foreign": "F",
                    "historical": "F",
                    "torEquipId": 10650,
                    "torStationId": 222,
                    "equipmentOwner": 30,
                    "symbolName": "1         "
                }
            ],
            "abnormCondStations": [],
            "abnormCondLines": [
                {
                    "lineId": 131,
                    "circuit": "FH63      ",
                    "enableFlag": "Y",
                    "userOrg": 123,
                    "lineFullName": "Joshua Falls - Reusens",
                    "underGround": "F",
                    "torCircuitId": 131,
                    "mileage": 9,
                    "historical": "F",
                    "voltageCir": 138,
                    "aepNonAep": "T",
                    "emsName": "MONEL   1REUSENS 1  ",
                    "emsId": 1996,
                    "nercRep": "F",
                    "kv": 138,
                    "ddcRegion": "Roanoke",
                    "dispRegion": "Roanoke-South",
                    "dispatchRegion": "Roanoke-South",
                    "ddc": "Roanoke",
                    "emsVoltageNumber": 138,
                    "createdBy": "TOA_APP",
                    "createdDate": 1285105614000,
                    "lastUpdatedBy": "TOA_APP",
                    "lastUpdatedDate": 1320651662000
                }
            ]
        },
        {
            "caseId": 441036,
            "eventId": 561586,
            "state": "OHIO",
            "district": "Newark",
            "startTime": 1371896160000,
            "isolated": "N",
            "details": "S.O. 14616 Rev. 19\r\nWest Morrison SW installed on feed to GE Hebron (Momentive). SW is bypassed w/ Switches open and tagged until ready to put into service. (See Drawing at Central Desk)",
            "title": "Dow Chemical - Kaiser Junction Sw. (69 kV)",
            "doubleCircuitOutage": "N",
            "properRelayOperation": "Y",
            "manual": "N",
            "diffEventStart": "N",
            "topsAnalysisComplete": "N",
            "topsApproved": "N",
            "createdBy": 1678,
            "createdDate": 1371898620000,
            "modifiedBy": 1561,
            "modifiedDate": 1372112280000,
            "isTemplate": "N",
            "abnormCondEquipments": [
                {
                    "equipmentId": 11438,
                    "equipmentType": "CB",
                    "equipmentName": "West Hebron/Kaiser Junction",
                    "equipmentFullName": "West Hebron/Kaiser Junction",
                    "stationId": 4763,
                    "voltage": "69",
                    "enableFlag": "Y",
                    "userOrg": 123,
                    "lastUpdatedBy": "TOA_APP",
                    "lastUpdatedDate": 1326488930000,
                    "createdBy": "TOA_APP",
                    "createdDate": 1285105528000,
                    "newEquip": "F",
                    "foreign": "F",
                    "historical": "F",
                    "torEquipId": 48241,
                    "torStationId": 12115,
                    "equipmentOwner": 30,
                    "symbolName": "A",
                    "description": "West Hebron/Kaiser Junction"
                },
                {
                    "equipmentId": 5356,
                    "equipmentType": "AB",
                    "equipmentName": "North Hebron  ",
                    "equipmentFullName": "North Hebron  ",
                    "stationId": 2327,
                    "voltage": "69",
                    "enableFlag": "Y",
                    "userOrg": 123,
                    "lastUpdatedBy": "TOA_APP",
                    "lastUpdatedDate": 1326488872000,
                    "createdBy": "TOA_APP",
                    "createdDate": 1285105525000,
                    "newEquip": "F",
                    "foreign": "F",
                    "historical": "F",
                    "torEquipId": 35690,
                    "torStationId": 5565,
                    "equipmentOwner": 30,
                    "symbolName": " ",
                    "description": "North Hebron  "
                },
                {
                    "equipmentId": 14751,
                    "equipmentType": "AB",
                    "equipmentName": "Kaiser Junction",
                    "equipmentFullName": "Kaiser Junction",
                    "stationId": 4763,
                    "voltage": "69",
                    "enableFlag": "Y",
                    "userOrg": 123,
                    "lastUpdatedBy": "TOA_APP",
                    "lastUpdatedDate": 1326488904000,
                    "createdBy": "TOA_APP",
                    "createdDate": 1285105527000,
                    "newEquip": "F",
                    "foreign": "F",
                    "historical": "F",
                    "torEquipId": 48247,
                    "torStationId": 12115,
                    "equipmentOwner": 30,
                    "symbolName": "  ",
                    "description": "Kaiser Junction"
                }
            ],
            "abnormCondStations": [],
            "abnormCondLines": [
                {
                    "lineId": 857,
                    "circuit": "HG17      ",
                    "enableFlag": "Y",
                    "userOrg": 123,
                    "lineFullName": "Dow Chemical - Kaiser Junction Sw.",
                    "underGround": "F",
                    "torCircuitId": 857,
                    "mileage": 4,
                    "historical": "F",
                    "voltageCir": 69,
                    "aepNonAep": "T",
                    "nercRep": "F",
                    "kv": 69,
                    "ddcRegion": "Columbus",
                    "dispRegion": "Columbus Central",
                    "dispatchRegion": "Ohio-South",
                    "ddc": "Columbus",
                    "createdBy": "TOA_APP",
                    "createdDate": 1285105614000,
                    "lastUpdatedBy": "TOA_APP",
                    "lastUpdatedDate": 1320651676000
                }
            ]
        },
        {
            "caseId": 431681,
            "eventId": -1,
            "state": "OHIO",
            "district": "Columbus",
            "startTime": 1367423280000,
            "isolated": "N",
            "details": "At Marion: 138kv cap bank 7 non-critical alarm",
            "troubleInfo": "At Marion: 138kv cap bank 7 non-critical alarm",
            "title": "Marion Road",
            "doubleCircuitOutage": "N",
            "properRelayOperation": "Y",
            "manual": "N",
            "diffEventStart": "N",
            "priority": 3,
            "topsAnalysisComplete": "N",
            "topsApproved": "N",
            "createdBy": 873,
            "createdDate": 1367444040000,
            "modifiedBy": 1678,
            "modifiedDate": 1367446320000,
            "isTemplate": "N",
            "abnormCondEquipments": [],
            "abnormCondStations": [
                {
                    "stationName": "Marion Road",
                    "torStationId": 857,
                    "regionName": "Columbus",
                    "areaName": "Columbus",
                    "transmissionDispatchCenterId": 23,
                    "transmissionDispatchCenter": "Columbus Central",
                    "transmissionDispatchCenterPhone": "614-413-2180",
                    "distributionDispatchCenterId": 12,
                    "distributionDispatchCenter": "Columbus Metro",
                    "distributionDispatchCenterPhone": "614-413-7099",
                    "hasOpenCheckIns": false,
                    "phone": "614-444-1732",
                    "county": "FRANKLIN",
                    "state": "OH",
                    "directions": "869 MARION RD  COLUMBUS",
                    "latitude": "39.92222867",
                    "longitude": "-82.9712871",
                    "contacts": "614 462 3333",
                    "district": "COL",
                    "restrictedFlag": false,
                    "hazardFlag": false,
                    "refreshDate": 1393952077531,
                    "stationId": 691,
                    "hasHazard": false
                }
            ],
            "abnormCondLines": []
        },
        {
            "caseId": 408733,
            "eventId": -1,
            "state": "OHIO",
            "district": "Columbus",
            "startTime": 1215799260000,
            "isolated": "N",
            "details": "DO NOT OPERATE. Control rod broken.",
            "title": "HAYDEN",
            "doubleCircuitOutage": "N",
            "properRelayOperation": "N",
            "manual": "N",
            "diffEventStart": "Y",
            "priority": 1,
            "topsAnalysisComplete": "N",
            "topsApproved": "N",
            "createdBy": 1776,
            "createdDate": 1215799260000,
            "modifiedBy": 5928,
            "modifiedDate": 1362162300000,
            "isTemplate": "N",
            "deviceId": 34896,
            "abnormCondEquipments": [
                {
                    "equipmentId": 13284,
                    "equipmentType": "AB",
                    "equipmentName": "Hyatt",
                    "equipmentFullName": "Hyatt",
                    "stationId": 658,
                    "voltage": "345",
                    "enableFlag": "Y",
                    "userOrg": 123,
                    "lastUpdatedBy": "TOA_APP",
                    "lastUpdatedDate": 1326488872000,
                    "createdBy": "TOA_APP",
                    "createdDate": 1285105526000,
                    "newEquip": "F",
                    "foreign": "F",
                    "historical": "F",
                    "torEquipId": 39934,
                    "torStationId": 796,
                    "equipmentOwner": 30,
                    "symbolName": " ",
                    "description": "Hyatt"
                }
            ],
            "abnormCondStations": [],
            "abnormCondLines": []
        },
        {
            "caseId": 437986,
            "eventId": 554886,
            "state": "VIRGINIA",
            "startTime": 1370560740000,
            "isolated": "Y",
            "details": "Transfer Trip Abnormal Alarms/pilot wire abnormal\r\nREQ 10915",
            "operatingArrangements": "No clearance issued.",
            "troubleInfo": "Opossum Creek - Joshua Falls PW & TT remains cutout due to trouble.",
            "title": "Joshua Falls - Opossum Creek (138 kV); Opossum Creek - Reusens (138 kV)",
            "doubleCircuitOutage": "N",
            "properRelayOperation": "Y",
            "manual": "N",
            "diffEventStart": "N",
            "topsAnalysisComplete": "N",
            "topsApproved": "N",
            "createdBy": 1048,
            "createdDate": 1370561280000,
            "modifiedBy": 1342,
            "modifiedDate": 1371498420000,
            "isTemplate": "N",
            "abnormCondEquipments": [
                {
                    "equipmentId": 11725,
                    "equipmentType": "CB",
                    "equipmentName": "East Lynchburg",
                    "equipmentFullName": "East Lynchburg",
                    "stationId": 525,
                    "voltage": "138",
                    "enableFlag": "Y",
                    "emsEquipmentId": "5469",
                    "userOrg": 123,
                    "lastUpdatedBy": "TOA_APP",
                    "lastUpdatedDate": 1326488926000,
                    "createdBy": "TOA_APP",
                    "createdDate": 1285105528000,
                    "newEquip": "F",
                    "foreign": "F",
                    "historical": "F",
                    "torEquipId": 2571,
                    "torStationId": 309,
                    "emsName": "OPOSSUMCB1  ",
                    "emsVoltage": 138,
                    "equipmentOwner": 30,
                    "symbolName": "B1",
                    "description": "East Lynchburg"
                }
            ],
            "abnormCondStations": [],
            "abnormCondLines": [
                {
                    "lineId": 168,
                    "circuit": "FM76      ",
                    "enableFlag": "Y",
                    "userOrg": 123,
                    "lineFullName": "Opossum Creek - Reusens",
                    "underGround": "F",
                    "torCircuitId": 168,
                    "mileage": 14,
                    "historical": "F",
                    "voltageCir": 138,
                    "aepNonAep": "T",
                    "emsName": "GRAVESMI1REUSENS 1  ",
                    "emsId": 1881,
                    "nercRep": "F",
                    "kv": 138,
                    "ddcRegion": "Roanoke",
                    "dispRegion": "Roanoke-South",
                    "dispatchRegion": "Roanoke-South",
                    "ddc": "Roanoke",
                    "emsVoltageNumber": 138,
                    "createdBy": "TOA_APP",
                    "createdDate": 1285105615000,
                    "lastUpdatedBy": "TOA_APP",
                    "lastUpdatedDate": 1320651698000
                },
                {
                    "lineId": 110,
                    "circuit": "FG55      ",
                    "enableFlag": "Y",
                    "userOrg": 123,
                    "lineFullName": "East Lynchburg - Joshua Falls",
                    "underGround": "F",
                    "torCircuitId": 110,
                    "mileage": 3,
                    "historical": "F",
                    "voltageCir": 138,
                    "aepNonAep": "T",
                    "emsName": "ELYNCHBU1JOSHUAFA1  ",
                    "emsId": 1818,
                    "nercRep": "F",
                    "kv": 138,
                    "ddcRegion": "Roanoke",
                    "dispRegion": "Roanoke-South",
                    "dispatchRegion": "Roanoke-South",
                    "ddc": "Roanoke",
                    "emsVoltageNumber": 138,
                    "createdBy": "TOA_APP",
                    "createdDate": 1285105614000,
                    "lastUpdatedBy": "TOA_APP",
                    "lastUpdatedDate": 1320651662000
                },
                {
                    "lineId": 131,
                    "circuit": "FH63      ",
                    "enableFlag": "Y",
                    "userOrg": 123,
                    "lineFullName": "Joshua Falls - Reusens",
                    "underGround": "F",
                    "torCircuitId": 131,
                    "mileage": 9,
                    "historical": "F",
                    "voltageCir": 138,
                    "aepNonAep": "T",
                    "emsName": "MONEL   1REUSENS 1  ",
                    "emsId": 1996,
                    "nercRep": "F",
                    "kv": 138,
                    "ddcRegion": "Roanoke",
                    "dispRegion": "Roanoke-South",
                    "dispatchRegion": "Roanoke-South",
                    "ddc": "Roanoke",
                    "emsVoltageNumber": 138,
                    "createdBy": "TOA_APP",
                    "createdDate": 1285105614000,
                    "lastUpdatedBy": "TOA_APP",
                    "lastUpdatedDate": 1320651662000
                },
                {
                    "lineId": 167,
                    "circuit": "FM73      ",
                    "enableFlag": "Y",
                    "userOrg": 123,
                    "lineFullName": "Opossum Creek - Peaksview",
                    "underGround": "F",
                    "torCircuitId": 167,
                    "mileage": 1,
                    "historical": "F",
                    "voltageCir": 138,
                    "aepNonAep": "T",
                    "emsName": "OPOSSUMC1PEAKSVIE1  ",
                    "emsId": 2047,
                    "nercRep": "F",
                    "kv": 138,
                    "ddcRegion": "Roanoke",
                    "dispRegion": "Roanoke-South",
                    "dispatchRegion": "Roanoke-South",
                    "ddc": "Roanoke",
                    "emsVoltageNumber": 138,
                    "createdBy": "TOA_APP",
                    "createdDate": 1285105613000,
                    "lastUpdatedBy": "TOA_APP",
                    "lastUpdatedDate": 1320651701000
                },
                {
                    "lineId": 109,
                    "circuit": "FG48      ",
                    "enableFlag": "Y",
                    "userOrg": 123,
                    "lineFullName": "East Lynchburg - Opossum Creek",
                    "underGround": "F",
                    "torCircuitId": 109,
                    "mileage": 2,
                    "historical": "F",
                    "voltageCir": 138,
                    "aepNonAep": "T",
                    "emsName": "ELYNCHBU1OPOSSUMC1  ",
                    "emsId": 1819,
                    "nercRep": "F",
                    "kv": 138,
                    "ddcRegion": "Roanoke",
                    "dispRegion": "Roanoke-South",
                    "dispatchRegion": "Roanoke-South",
                    "ddc": "Roanoke",
                    "emsVoltageNumber": 138,
                    "createdBy": "TOA_APP",
                    "createdDate": 1285105614000,
                    "lastUpdatedBy": "TOA_APP",
                    "lastUpdatedDate": 1320651662000
                },
                {
                    "lineId": 132,
                    "circuit": "FH66      ",
                    "enableFlag": "Y",
                    "userOrg": 123,
                    "lineFullName": "Joshua Falls - Opossum Creek",
                    "underGround": "F",
                    "torCircuitId": 132,
                    "mileage": 5,
                    "historical": "F",
                    "voltageCir": 138,
                    "aepNonAep": "T",
                    "emsName": "JOSHUAFA1OPOSSUMC1  ",
                    "emsId": 1934,
                    "nercRep": "F",
                    "kv": 138,
                    "ddcRegion": "Roanoke",
                    "dispRegion": "Roanoke-South",
                    "dispatchRegion": "Roanoke-South",
                    "ddc": "Roanoke",
                    "emsVoltageNumber": 138,
                    "createdBy": "TOA_APP",
                    "createdDate": 1285105614000,
                    "lastUpdatedBy": "TOA_APP",
                    "lastUpdatedDate": 1320651662000
                }
            ]
        },
        {
            "caseId": 432904,
            "eventId": -1,
            "state": "VIRGINIA",
            "startTime": 1368077220000,
            "isolated": "N",
            "details": "Recurring CB MA Alarm Delle Minsub 138kV Alarm ",
            "troubleInfo": "Low hydraulic fluid on Tr 1 138kV CB G2 due to leak.  Personnel unable to locate source of leak at this time.\r\n\r\nNotify Dale Arrington immediately anytime this alarm seals in as per M. Cheek and C. Foggy.",
            "title": "Joshua Falls - Tr. 1 138KV - CB G2 ",
            "doubleCircuitOutage": "N",
            "properRelayOperation": "Y",
            "manual": "N",
            "diffEventStart": "N",
            "topsAnalysisComplete": "N",
            "topsApproved": "N",
            "createdBy": 1354,
            "createdDate": 1368089760000,
            "modifiedBy": 1378,
            "modifiedDate": 1368206280000,
            "isTemplate": "N",
            "abnormCondEquipments": [
                {
                    "equipmentId": 8548,
                    "equipmentType": "CB",
                    "equipmentName": "Tr. 1",
                    "equipmentFullName": "Tr. 1",
                    "stationId": 35,
                    "voltage": "138",
                    "enableFlag": "Y",
                    "emsEquipmentId": "5186",
                    "userOrg": 123,
                    "lastUpdatedBy": "TOA_APP",
                    "lastUpdatedDate": 1326488936000,
                    "createdBy": "TOA_APP",
                    "createdDate": 1285105528000,
                    "newEquip": "F",
                    "foreign": "F",
                    "historical": "F",
                    "torEquipId": 2395,
                    "torStationId": 222,
                    "emsName": "JOSHUAFAG2  ",
                    "emsVoltage": 138,
                    "equipmentOwner": 30,
                    "symbolName": "G2",
                    "description": "Tr. 1"
                },
                {
                    "equipmentId": 18012,
                    "equipmentType": "BUS",
                    "stationId": 35,
                    "voltage": "138",
                    "enableFlag": "Y",
                    "userOrg": 123,
                    "lastUpdatedBy": "TOA_APP",
                    "lastUpdatedDate": 1326488927000,
                    "createdBy": "TOA_APP",
                    "createdDate": 1285105528000,
                    "newEquip": "F",
                    "foreign": "F",
                    "historical": "F",
                    "torEquipId": 10492,
                    "torStationId": 222,
                    "equipmentOwner": 30,
                    "symbolName": "2         "
                },
                {
                    "equipmentId": 11687,
                    "equipmentType": "BUS",
                    "stationId": 35,
                    "voltage": "138",
                    "enableFlag": "Y",
                    "userOrg": 123,
                    "lastUpdatedBy": "TOA_APP",
                    "lastUpdatedDate": 1326488924000,
                    "createdBy": "TOA_APP",
                    "createdDate": 1285105528000,
                    "newEquip": "F",
                    "foreign": "F",
                    "historical": "F",
                    "torEquipId": 10650,
                    "torStationId": 222,
                    "equipmentOwner": 30,
                    "symbolName": "1         "
                }
            ],
            "abnormCondStations": [],
            "abnormCondLines": [
                {
                    "lineId": 131,
                    "circuit": "FH63      ",
                    "enableFlag": "Y",
                    "userOrg": 123,
                    "lineFullName": "Joshua Falls - Reusens",
                    "underGround": "F",
                    "torCircuitId": 131,
                    "mileage": 9,
                    "historical": "F",
                    "voltageCir": 138,
                    "aepNonAep": "T",
                    "emsName": "MONEL   1REUSENS 1  ",
                    "emsId": 1996,
                    "nercRep": "F",
                    "kv": 138,
                    "ddcRegion": "Roanoke",
                    "dispRegion": "Roanoke-South",
                    "dispatchRegion": "Roanoke-South",
                    "ddc": "Roanoke",
                    "emsVoltageNumber": 138,
                    "createdBy": "TOA_APP",
                    "createdDate": 1285105614000,
                    "lastUpdatedBy": "TOA_APP",
                    "lastUpdatedDate": 1320651662000
                }
            ]
        },
        {
            "caseId": 441036,
            "eventId": 561586,
            "state": "OHIO",
            "district": "Newark",
            "startTime": 1371896160000,
            "isolated": "N",
            "details": "S.O. 14616 Rev. 19\r\nWest Morrison SW installed on feed to GE Hebron (Momentive). SW is bypassed w/ Switches open and tagged until ready to put into service. (See Drawing at Central Desk)",
            "title": "Dow Chemical - Kaiser Junction Sw. (69 kV)",
            "doubleCircuitOutage": "N",
            "properRelayOperation": "Y",
            "manual": "N",
            "diffEventStart": "N",
            "topsAnalysisComplete": "N",
            "topsApproved": "N",
            "createdBy": 1678,
            "createdDate": 1371898620000,
            "modifiedBy": 1561,
            "modifiedDate": 1372112280000,
            "isTemplate": "N",
            "abnormCondEquipments": [
                {
                    "equipmentId": 11438,
                    "equipmentType": "CB",
                    "equipmentName": "West Hebron/Kaiser Junction",
                    "equipmentFullName": "West Hebron/Kaiser Junction",
                    "stationId": 4763,
                    "voltage": "69",
                    "enableFlag": "Y",
                    "userOrg": 123,
                    "lastUpdatedBy": "TOA_APP",
                    "lastUpdatedDate": 1326488930000,
                    "createdBy": "TOA_APP",
                    "createdDate": 1285105528000,
                    "newEquip": "F",
                    "foreign": "F",
                    "historical": "F",
                    "torEquipId": 48241,
                    "torStationId": 12115,
                    "equipmentOwner": 30,
                    "symbolName": "A",
                    "description": "West Hebron/Kaiser Junction"
                },
                {
                    "equipmentId": 5356,
                    "equipmentType": "AB",
                    "equipmentName": "North Hebron  ",
                    "equipmentFullName": "North Hebron  ",
                    "stationId": 2327,
                    "voltage": "69",
                    "enableFlag": "Y",
                    "userOrg": 123,
                    "lastUpdatedBy": "TOA_APP",
                    "lastUpdatedDate": 1326488872000,
                    "createdBy": "TOA_APP",
                    "createdDate": 1285105525000,
                    "newEquip": "F",
                    "foreign": "F",
                    "historical": "F",
                    "torEquipId": 35690,
                    "torStationId": 5565,
                    "equipmentOwner": 30,
                    "symbolName": " ",
                    "description": "North Hebron  "
                },
                {
                    "equipmentId": 14751,
                    "equipmentType": "AB",
                    "equipmentName": "Kaiser Junction",
                    "equipmentFullName": "Kaiser Junction",
                    "stationId": 4763,
                    "voltage": "69",
                    "enableFlag": "Y",
                    "userOrg": 123,
                    "lastUpdatedBy": "TOA_APP",
                    "lastUpdatedDate": 1326488904000,
                    "createdBy": "TOA_APP",
                    "createdDate": 1285105527000,
                    "newEquip": "F",
                    "foreign": "F",
                    "historical": "F",
                    "torEquipId": 48247,
                    "torStationId": 12115,
                    "equipmentOwner": 30,
                    "symbolName": "  ",
                    "description": "Kaiser Junction"
                }
            ],
            "abnormCondStations": [],
            "abnormCondLines": [
                {
                    "lineId": 857,
                    "circuit": "HG17      ",
                    "enableFlag": "Y",
                    "userOrg": 123,
                    "lineFullName": "Dow Chemical - Kaiser Junction Sw.",
                    "underGround": "F",
                    "torCircuitId": 857,
                    "mileage": 4,
                    "historical": "F",
                    "voltageCir": 69,
                    "aepNonAep": "T",
                    "nercRep": "F",
                    "kv": 69,
                    "ddcRegion": "Columbus",
                    "dispRegion": "Columbus Central",
                    "dispatchRegion": "Ohio-South",
                    "ddc": "Columbus",
                    "createdBy": "TOA_APP",
                    "createdDate": 1285105614000,
                    "lastUpdatedBy": "TOA_APP",
                    "lastUpdatedDate": 1320651676000
                }
            ]
        }
    ],
            internalGetOne = function() {
                var deferred = $.Deferred(),
                        results = internalAbnormalConditions[0];
                deferred.resolve(results, 'success', null);
                return deferred.promise();
            },
            internalFindByStationId = function(stationId) {
                var deferred = $.Deferred(),
                        results = internalAbnormalConditions;
                deferred.resolve(results, 'success', null);
                return deferred.promise();
            },
            abnormalConditions = {
                getOne: function() {
                    return internalGetOne();
                },
                findByStationId: function(stationId) {
                    return internalFindByStationId(stationId);
                }

            };

    return abnormalConditions;

});